// ──────────────────────────────────────────────────────────
// 40 Subjects – canonical data layer
// Sourced from Takween Tutors WordPress export content
// ──────────────────────────────────────────────────────────

export interface Subject {
    slug: string;
    name: string;
    level: "GCSE" | "A-Level" | "11+" | "BTEC";
    icon: string;
    color: string; // tailwind gradient
    description: string;
    longDescription: string;
    examBoards: string[];
    keyTopics: string[];
}

export const allSubjects: Subject[] = [
    // ── GCSE Subjects ──
    { slug: "gcse-maths", name: "GCSE Maths", level: "GCSE", icon: "📐", color: "from-blue-500 to-indigo-600", description: "Build a strong foundation in number, algebra, geometry, and statistics.", longDescription: "Our GCSE Maths tutoring covers the full curriculum from numbers and algebra to geometry, statistics, and probability. Tutors provide exam-focused practice, ensuring students gain confidence and achieve the grades they deserve.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Algebra", "Geometry", "Statistics", "Number", "Ratio & Proportion"] },
    { slug: "gcse-biology", name: "GCSE Biology", level: "GCSE", icon: "🧬", color: "from-green-500 to-emerald-600", description: "Understand living organisms, ecosystems, and the human body.", longDescription: "From cell biology and genetics to ecology and evolution, our GCSE Biology tutoring helps students master the key concepts and develop strong exam technique for the highest grades.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Cell Biology", "Organisation", "Infection", "Bioenergetics", "Ecology"] },
    { slug: "gcse-chemistry", name: "GCSE Chemistry", level: "GCSE", icon: "🧪", color: "from-purple-500 to-violet-600", description: "Master atomic structure, bonding, and chemical reactions.", longDescription: "Our Chemistry tutoring covers atomic structure, bonding, quantitative chemistry, chemical changes, and organic chemistry. We focus on understanding and exam technique to boost grades.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Atomic Structure", "Bonding", "Quantitative Chemistry", "Chemical Changes", "Organic Chemistry"] },
    { slug: "gcse-physics", name: "GCSE Physics", level: "GCSE", icon: "⚡", color: "from-amber-500 to-orange-600", description: "Explore energy, forces, waves, and the universe.", longDescription: "From forces and motion to energy, waves, and electromagnetism, our Physics tutoring delivers clear explanations and exam-ready practice to help students achieve excellent results.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Energy", "Forces", "Waves", "Electricity", "Magnetism"] },
    { slug: "gcse-english-literature", name: "GCSE English Literature", level: "GCSE", icon: "📚", color: "from-rose-500 to-pink-600", description: "Analyse prose, poetry, and drama with confidence.", longDescription: "Our English Literature tutoring covers Shakespeare, 19th-century novels, modern texts, and poetry. We teach analytical skills, essay technique, and close reading to help students write with confidence.", examBoards: ["AQA", "Edexcel", "OCR", "WJEC"], keyTopics: ["Shakespeare", "Poetry Anthology", "Modern Texts", "19th Century Novel", "Unseen Poetry"] },
    { slug: "gcse-english-language", name: "GCSE English Language", level: "GCSE", icon: "📝", color: "from-sky-500 to-cyan-600", description: "Sharpen reading comprehension and creative writing skills.", longDescription: "We help students master reading comprehension, creative writing, transactional writing, and spoken language. Our tutors focus on building skills and exam technique for maximum marks.", examBoards: ["AQA", "Edexcel", "OCR", "WJEC"], keyTopics: ["Creative Writing", "Reading Comprehension", "Transactional Writing", "Language Analysis", "Spoken Language"] },
    { slug: "gcse-spanish", name: "GCSE Spanish", level: "GCSE", icon: "🇪🇸", color: "from-red-500 to-orange-600", description: "Develop listening, speaking, reading, and writing in Spanish.", longDescription: "Our Spanish tutoring builds confidence across all four skills. Tutors focus on vocabulary, grammar, exam technique, and conversational fluency to help students excel.", examBoards: ["AQA", "Edexcel"], keyTopics: ["Vocabulary", "Grammar", "Listening", "Speaking", "Writing"] },
    { slug: "gcse-geography", name: "GCSE Geography", level: "GCSE", icon: "🌍", color: "from-teal-500 to-cyan-600", description: "Explore physical and human geography with real-world case studies.", longDescription: "From natural hazards and ecosystems to urban issues and resource management, our Geography tutoring uses case studies and fieldwork skills to build deep understanding.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Natural Hazards", "Living World", "Physical Landscapes", "Urban Issues", "Resource Management"] },
    { slug: "gcse-history", name: "GCSE History", level: "GCSE", icon: "🏰", color: "from-yellow-600 to-amber-700", description: "Analyse key events, sources, and historical interpretations.", longDescription: "Our History tutoring covers period studies, thematic studies, and British depth studies. We develop source analysis, essay writing, and chronological understanding.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Medicine Through Time", "Cold War", "Norman England", "Weimar & Nazi Germany", "Elizabethan England"] },
    { slug: "gcse-french", name: "GCSE French", level: "GCSE", icon: "🇫🇷", color: "from-blue-600 to-indigo-700", description: "Build fluency in French across all four language skills.", longDescription: "Our French tutoring covers listening, speaking, reading, and writing. We focus on grammar, vocabulary, exam technique, and real-world communication to boost confidence and grades.", examBoards: ["AQA", "Edexcel"], keyTopics: ["Grammar", "Vocabulary", "Listening Comprehension", "Speaking", "Writing"] },
    { slug: "gcse-computer-science", name: "GCSE Computer Science", level: "GCSE", icon: "💻", color: "from-slate-600 to-zinc-700", description: "Learn programming, algorithms, and computational thinking.", longDescription: "From Python programming and algorithms to data representation and networks, our Computer Science tutoring builds strong practical and theoretical foundations.", examBoards: ["AQA", "OCR", "Edexcel"], keyTopics: ["Programming", "Algorithms", "Data Representation", "Networks", "Cyber Security"] },
    { slug: "gcse-religious-studies", name: "GCSE Religious Studies", level: "GCSE", icon: "🕊️", color: "from-indigo-500 to-purple-600", description: "Explore beliefs, teachings, and ethical themes across religions.", longDescription: "Our Religious Studies tutoring covers Christianity, Islam, and thematic studies including relationships, life and death, peace and conflict, and crime and punishment.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Christianity", "Islam", "Philosophy of Religion", "Ethics", "Thematic Studies"] },
    { slug: "gcse-combined-science", name: "GCSE Combined Science", level: "GCSE", icon: "🔬", color: "from-emerald-500 to-green-600", description: "Cover biology, chemistry, and physics in one comprehensive course.", longDescription: "Our Combined Science tutoring covers all three sciences in a single, streamlined approach. We ensure students are well-prepared across biology, chemistry, and physics for their double award.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Cell Biology", "Atomic Structure", "Energy", "Chemical Changes", "Forces"] },
    { slug: "gcse-business", name: "GCSE Business", level: "GCSE", icon: "💼", color: "from-cyan-500 to-blue-600", description: "Understand how businesses operate, grow, and compete.", longDescription: "Our Business tutoring covers enterprise, marketing, finance, operations, and human resources. We help students develop strong analytical and evaluative skills for exam success.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Enterprise", "Marketing", "Finance", "Operations", "Human Resources"] },
    { slug: "gcse-art", name: "GCSE Art & Design", level: "GCSE", icon: "🎨", color: "from-pink-500 to-rose-600", description: "Develop creative skills across drawing, painting, and mixed media.", longDescription: "Our Art tutoring supports portfolio development, observational drawing, critical analysis, and exam preparation. We help students express their creativity with confidence and technique.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Drawing", "Painting", "Mixed Media", "Photography", "Critical Analysis"] },
    { slug: "gcse-music", name: "GCSE Music", level: "GCSE", icon: "🎵", color: "from-violet-500 to-purple-600", description: "Study performance, composition, and music appreciation.", longDescription: "Our Music tutoring covers performance skills, composition techniques, and listening/appraising across different styles and periods. We support practical and written components.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Performance", "Composition", "Listening", "Music Theory", "Analysis"] },
    { slug: "gcse-pe", name: "GCSE Physical Education", level: "GCSE", icon: "🏃", color: "from-green-600 to-lime-600", description: "Explore anatomy, physiology, and sport psychology.", longDescription: "Our PE tutoring covers anatomy, physiology, movement analysis, sport psychology, and socio-cultural influences. We help students master both practical and theoretical components.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Anatomy", "Physiology", "Sport Psychology", "Training Methods", "Health & Fitness"] },
    { slug: "gcse-sociology", name: "GCSE Sociology", level: "GCSE", icon: "👥", color: "from-orange-500 to-amber-600", description: "Understand society, culture, and social structures.", longDescription: "Our Sociology tutoring covers families, education, crime, and social stratification. We help students develop strong analytical and evaluative skills using key sociological theories.", examBoards: ["AQA", "WJEC"], keyTopics: ["Families", "Education", "Crime & Deviance", "Social Stratification", "Research Methods"] },
    { slug: "gcse-psychology", name: "GCSE Psychology", level: "GCSE", icon: "🧠", color: "from-fuchsia-500 to-pink-600", description: "Explore the science of mind and behaviour.", longDescription: "Our Psychology tutoring covers memory, perception, development, social influence, and research methods. We teach students to apply psychological theories and evaluate research.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Memory", "Perception", "Development", "Social Influence", "Research Methods"] },
    { slug: "gcse-design-technology", name: "GCSE Design & Technology", level: "GCSE", icon: "⚙️", color: "from-zinc-500 to-slate-600", description: "Design, make, and evaluate products using core principles.", longDescription: "Our D&T tutoring covers materials, manufacturing, design principles, and the iterative design process. We support both the non-exam assessment (NEA) and written exam preparation.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Materials", "Manufacturing", "Design Principles", "Systems", "NEA Portfolio"] },

    // ── A-Level Subjects ──
    { slug: "a-level-maths", name: "A-Level Maths", level: "A-Level", icon: "📐", color: "from-blue-600 to-indigo-700", description: "Master pure maths, statistics, and mechanics at advanced level.", longDescription: "Our A-Level Maths tutoring covers pure mathematics, statistics, and mechanics. We focus on deep conceptual understanding, problem-solving skills, and rigorous exam preparation.", examBoards: ["AQA", "Edexcel", "OCR", "OCR MEI"], keyTopics: ["Pure Maths", "Statistics", "Mechanics", "Differentiation", "Integration"] },
    { slug: "a-level-further-maths", name: "A-Level Further Maths", level: "A-Level", icon: "🧮", color: "from-indigo-600 to-blue-700", description: "Challenge yourself with complex mathematical concepts.", longDescription: "Our Further Maths tutoring covers complex numbers, matrices, further calculus, and decision maths. Ideal for students pursuing STEM degrees at top universities.", examBoards: ["AQA", "Edexcel", "OCR", "OCR MEI"], keyTopics: ["Complex Numbers", "Matrices", "Further Calculus", "Hyperbolic Functions", "Decision Maths"] },
    { slug: "a-level-biology", name: "A-Level Biology", level: "A-Level", icon: "🧬", color: "from-green-600 to-emerald-700", description: "Deepen your understanding of biological processes and systems.", longDescription: "Our A-Level Biology tutoring covers molecules, cells, organisms, genetics, and ecosystems. We develop practical skills and essay technique alongside content mastery.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Biological Molecules", "Cells", "Genetics", "Energy Transfers", "Ecosystems"] },
    { slug: "a-level-chemistry", name: "A-Level Chemistry", level: "A-Level", icon: "🧪", color: "from-purple-600 to-violet-700", description: "Explore physical, inorganic, and organic chemistry in depth.", longDescription: "Our A-Level Chemistry tutoring covers physical, inorganic, and organic chemistry. We focus on understanding, calculations, practical skills, and synoptic exam questions.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Physical Chemistry", "Inorganic Chemistry", "Organic Chemistry", "Analytical Techniques", "Thermodynamics"] },
    { slug: "a-level-physics", name: "A-Level Physics", level: "A-Level", icon: "⚡", color: "from-amber-600 to-orange-700", description: "Tackle advanced mechanics, electricity, and quantum physics.", longDescription: "Our A-Level Physics tutoring covers mechanics, electricity, waves, fields, and nuclear/particle physics. We develop mathematical fluency and deep physical understanding.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Mechanics", "Electricity", "Waves & Optics", "Fields", "Nuclear Physics"] },
    { slug: "a-level-english-literature", name: "A-Level English Literature", level: "A-Level", icon: "📚", color: "from-rose-600 to-pink-700", description: "Engage critically with poetry, prose, and drama texts.", longDescription: "Our A-Level English Literature tutoring develops sophisticated analytical writing, critical theory application, and confident engagement with complex literary texts across all genres.", examBoards: ["AQA", "Edexcel", "OCR", "WJEC"], keyTopics: ["Tragedy", "Political Writing", "Love Poetry", "Gothic Literature", "Critical Theory"] },
    { slug: "a-level-psychology", name: "A-Level Psychology", level: "A-Level", icon: "🧠", color: "from-fuchsia-600 to-pink-700", description: "Study human behaviour, cognition, and mental health.", longDescription: "Our Psychology tutoring covers approaches, biopsychology, research methods, psychopathology, and optional topics. We develop evaluation skills and exam technique.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Approaches", "Biopsychology", "Research Methods", "Psychopathology", "Social Influence"] },
    { slug: "a-level-economics", name: "A-Level Economics", level: "A-Level", icon: "📈", color: "from-emerald-600 to-teal-700", description: "Analyse microeconomics, macroeconomics, and global markets.", longDescription: "Our Economics tutoring covers microeconomics, macroeconomics, and international economics. We develop analytical and evaluative essay skills alongside data interpretation.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Microeconomics", "Macroeconomics", "International Trade", "Market Failure", "Fiscal Policy"] },
    { slug: "a-level-philosophy", name: "A-Level Philosophy", level: "A-Level", icon: "💭", color: "from-slate-600 to-gray-700", description: "Explore epistemology, ethics, and the philosophy of mind.", longDescription: "Our Philosophy tutoring covers epistemology, moral philosophy, philosophy of mind, and philosophy of religion. We develop clear, rigorous argumentative writing.", examBoards: ["AQA", "OCR"], keyTopics: ["Epistemology", "Moral Philosophy", "Philosophy of Mind", "Philosophy of Religion", "Metaphysics"] },
    { slug: "a-level-politics", name: "A-Level Politics", level: "A-Level", icon: "🏛️", color: "from-red-600 to-rose-700", description: "Study UK government, political ideologies, and global politics.", longDescription: "Our Politics tutoring covers UK government, political participation, core ideologies, and either US politics or global politics. We develop strong essay-writing and analytical skills.", examBoards: ["AQA", "Edexcel"], keyTopics: ["UK Government", "Political Participation", "Liberalism", "Conservatism", "Socialism"] },
    { slug: "a-level-sociology", name: "A-Level Sociology", level: "A-Level", icon: "👥", color: "from-orange-600 to-amber-700", description: "Critically analyse society, inequality, and social identity.", longDescription: "Our A-Level Sociology tutoring covers education, families, crime, beliefs, and theory. We develop strong evaluative skills using perspectives like Marxism, feminism, and functionalism.", examBoards: ["AQA", "OCR", "WJEC"], keyTopics: ["Education", "Families & Households", "Crime & Deviance", "Theory & Methods", "Beliefs in Society"] },
    { slug: "a-level-history", name: "A-Level History", level: "A-Level", icon: "🏰", color: "from-yellow-700 to-amber-800", description: "Study historical breadth studies, depth studies, and coursework.", longDescription: "Our A-Level History tutoring covers breadth studies, depth studies, and NEA coursework. We help students develop source evaluation, essay structure, and strong historical argument.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Tudors", "Russia 1917–1991", "Civil Rights", "British Empire", "NEA Coursework"] },
    { slug: "a-level-computer-science", name: "A-Level Computer Science", level: "A-Level", icon: "💻", color: "from-slate-700 to-zinc-800", description: "Master algorithms, programming, and computational theory.", longDescription: "Our A-Level Computer Science tutoring covers OOP, algorithms, data structures, databases, and the NEA programming project. We build both theoretical knowledge and practical coding skills.", examBoards: ["AQA", "OCR", "Edexcel"], keyTopics: ["OOP", "Algorithms", "Data Structures", "Databases", "NEA Project"] },
    { slug: "a-level-business", name: "A-Level Business", level: "A-Level", icon: "💼", color: "from-cyan-600 to-blue-700", description: "Explore strategic business management and decision-making.", longDescription: "Our Business tutoring covers marketing, finance, operations, human resources, and strategic decision-making. We develop strong analytical and evaluative essay technique.", examBoards: ["AQA", "Edexcel", "OCR"], keyTopics: ["Marketing Strategy", "Financial Ratios", "Operations Management", "HR Strategy", "Strategic Decision Making"] },

    // ── 11+ / BTEC ──
    { slug: "11-plus-maths", name: "11+ Maths", level: "11+", icon: "🎯", color: "from-blue-500 to-sky-600", description: "Prepare for the 11+ entrance exam with confidence.", longDescription: "Our 11+ Maths tutoring covers verbal reasoning, non-verbal reasoning, maths, and English. We build exam confidence through practice papers, timed tests, and progressive skill building.", examBoards: ["GL", "CEM", "ISEB"], keyTopics: ["Arithmetic", "Problem Solving", "Fractions & Decimals", "Geometry", "Data Handling"] },
    { slug: "11-plus-english", name: "11+ English", level: "11+", icon: "✍️", color: "from-rose-500 to-pink-600", description: "Build reading comprehension and creative writing for 11+ success.", longDescription: "Our 11+ English tutoring covers reading comprehension, creative writing, grammar, punctuation, and spelling. We build the skills and confidence needed for competitive entrance exams.", examBoards: ["GL", "CEM", "ISEB"], keyTopics: ["Comprehension", "Creative Writing", "Grammar", "Spelling", "Vocabulary"] },
    { slug: "11-plus-verbal-reasoning", name: "11+ Verbal Reasoning", level: "11+", icon: "🔤", color: "from-indigo-500 to-blue-600", description: "Develop verbal reasoning and problem-solving skills.", longDescription: "Our Verbal Reasoning tutoring covers word patterns, logic, analogies, and code-breaking. We use timed practice and progressive difficulty to build speed and accuracy.", examBoards: ["GL", "CEM"], keyTopics: ["Analogies", "Word Codes", "Logic", "Sequences", "Comprehension"] },
    { slug: "11-plus-non-verbal-reasoning", name: "11+ Non-Verbal Reasoning", level: "11+", icon: "🧩", color: "from-violet-500 to-purple-600", description: "Master spatial reasoning and pattern recognition.", longDescription: "Our Non-Verbal Reasoning tutoring covers pattern recognition, spatial reasoning, shapes, and transformations. We develop visual-spatial skills essential for 11+ exam success.", examBoards: ["GL", "CEM"], keyTopics: ["Patterns", "Sequences", "Spatial Reasoning", "Transformations", "Odd One Out"] },
    { slug: "btec-business", name: "BTEC Business", level: "BTEC", icon: "📊", color: "from-teal-600 to-emerald-700", description: "Explore applied business through coursework and controlled assessment.", longDescription: "Our BTEC Business tutoring supports unit assignments, controlled assessments, and exam units. We help students develop research, analysis, and professional writing skills.", examBoards: ["Pearson"], keyTopics: ["Exploring Business", "Developing a Marketing Campaign", "Personal Finance", "Recruitment", "Customer Service"] },
    { slug: "btec-health-social-care", name: "BTEC Health & Social Care", level: "BTEC", icon: "🏥", color: "from-pink-600 to-rose-700", description: "Study health, care, and social services through practical learning.", longDescription: "Our BTEC Health & Social Care tutoring covers human lifespan development, health and social care values, and health and wellbeing. We support coursework, exams, and practical skills.", examBoards: ["Pearson"], keyTopics: ["Human Lifespan Development", "Health & Social Care Values", "Health & Wellbeing", "Anatomy", "Care Planning"] },
];

// Lookup by slug
export function getSubjectBySlug(slug: string): Subject | undefined {
    return allSubjects.find(s => s.slug === slug);
}

// Group by level
export function getSubjectsByLevel(level: Subject["level"]): Subject[] {
    return allSubjects.filter(s => s.level === level);
}
